context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Compresor PipeWire"
            media.name        = "Compresor PipeWire"
            filter.graph = {
                nodes = [
                    {
                        type  = builtin
                        name  = compressor
                        label = compressor
                        config = {
                            threshold = 0.125
                            ratio     = 2.0
                            attack    = 20.0
                            release   = 250.0
                            makeup    = 1.0
                            knee      = 2.828430
                            bypass    = 0
                        }
                    }
                ]
            }
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name   = "effect_input.comp"
                media.class = "Audio/Sink"
            }
            playback.props = {
                node.name   = "effect_output.comp"
                node.passive = true
            }
        }
    }
]